# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org  (for organization related metrics)
          #  - read:user (for user related data)
          #  - repo      (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: aMarCruz
          template: classic
          base: header, activity, community, repositories, metadata
          config_octicon: yes
          config_timezone: America/Mexico_City
          commits_authoring: amarcruz1@gmail.com, amarcruz@yahoo.com, amarcruzbox-git@yahoo.com, amarcruz@users.noreply.github.com
          filename: images/github-metrics.svg
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_languages: yes
          plugin_languages_limit: 5
          plugin_languages_threshold: 2%
          plugin_languages_details: lines, percentage
          plugin_languages_categories: markup, programming
          plugin_languages_recent_categories: markup, programming
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 3174665
          repositories_affiliations: owner, collaborator
          extras_css: |
            { h1: margin-bottom: 8px; h2, h2.field: margin-bottom: 4px }
          extras_js: |
            { const h1 = document.querySelector('h1'); h1 && h1.remove() }
